const PRODUCTS = [
  {
    "asin": "B0DCLXRD5X",
    "title": "Fogão Elétrico Portátil Cooktop Elgin Double Cook 2 Bocas - 220V",
    "image": "https://m.media-amazon.com/images/I/41z7d-LlVEL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 84.9,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 1281,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0DCLXRD5X?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B0B3SJ345V",
    "title": "SUGGAR DEPURADOR DE AR SLIM 60CM 3 VEL. PRETO 110V DPS161PT",
    "image": "https://m.media-amazon.com/images/I/41q3C2LevmL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 336.98,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 5352,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0B3SJ345V?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B0FP1251TD",
    "title": "Suporte com Rodinhas Movel Ajustável Telescópico para Geladeira Fogão Máquina de Lavar Móveis Pesados até 200kgs Base Antider",
    "image": "https://m.media-amazon.com/images/I/41iY1Zn43VL._AC_SL1072_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 29.89,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 678,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0FP1251TD?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B0B3SHMB2W",
    "title": "SUGGAR DEPURADOR DE AR SLIM 80CM 3 VEL. PRETO 110V DPS181PT",
    "image": "https://m.media-amazon.com/images/I/41reXjYlagL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 385.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 2109,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0B3SHMB2W?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B0876YDWVC",
    "title": "Dover-Roll Odor Defense Banheiro & Pia Lilás, Rolo com 50 Sacos para Lixo Pure Fresh",
    "image": "https://m.media-amazon.com/images/I/51DjpTGQlFL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 14.99,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 9611,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0876YDWVC?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B084R94R4S",
    "title": "Máquina de Lavar Electrolux 11kg Branca Essential Care com Easy Clean e Filtro Fiapos (LES11) - 127V",
    "image": "https://m.media-amazon.com/images/I/41+50Z4TgEL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1699.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 664,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B084R94R4S?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": true
  },
  {
    "asin": "B086WWQX1S",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina",
    "image": "https://m.media-amazon.com/images/I/61BJhE0GLIL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 25.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4333,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B086WWQX1S?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B00HGNXC8Q",
    "title": "Máquina de Lavar Panasonic 15kg Branca Função Vanish NA-F150B1W 127v",
    "image": "https://m.media-amazon.com/images/I/61gXZ2VqfdL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1926.77,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 224,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B00HGNXC8Q?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B08NWQHGR4",
    "title": "Artist Unknown - Pacote com 4 Cal�os de Borracha Redondos Pretos para Elevar e Estabilizar Lavadora, Secadora, Geladeira ou O",
    "image": "https://m.media-amazon.com/images/I/61nbiJ9iyTL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 14.49,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 3243,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B08NWQHGR4?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D7NPF9Z2",
    "title": "\"Capa Para Maquina De Lavar Brastemp Eletrolux Consul 07Kg 08Kg 09Kg 10Kg 11Kg12Kg 13Kg 14Kg 15Kg 16Kg 17Kg Impermeável Forra",
    "image": "https://m.media-amazon.com/images/I/61e0+ijy0pL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 39.9,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.4,
    "qtd_avaliacoes": 1484,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0D7NPF9Z2?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B09B929QDL",
    "title": "Máquina de Lavar 17kg Electrolux Essential Care com Cesto Inox, Jet&Clean e Ultra Filter (LED17)",
    "image": "https://m.media-amazon.com/images/I/41jXZmfuQoL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 2199.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 170,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B09B929QDL?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BSR6FFD8",
    "title": "SUGGAR LAVADORA DE ROUPAS LAVAMAX ECO 20KG 110V BRANCA LE2001BR",
    "image": "https://m.media-amazon.com/images/I/41rECLQvLwL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 750.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 974,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0BSR6FFD8?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B07CZ3R2P8",
    "title": "Refil Filtro Vela Purificador Soft Everest Original",
    "image": "https://m.media-amazon.com/images/I/41XhFbEHcKL._AC_SL1080_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 90.49,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1083,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B07CZ3R2P8?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0798XT2VK",
    "title": "Protetor De Geladeira ou Freezer Contra Queda Surtos de Energia 127V",
    "image": "https://m.media-amazon.com/images/I/516wjfTaZwL._AC_SL1125_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 45.14,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 5737,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0798XT2VK?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FLQJJ47J",
    "title": "Lava-Louças Electrolux 14 Serviços Inox com Programa Lava e Seca 220v LS14E",
    "image": "https://m.media-amazon.com/images/I/41+T6Xe5XKL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 3530.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 55,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0FLQJJ47J?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B085JFRRSW",
    "title": "MONDIAL Cooktop a Gás, 4 Bocas, Preto/Inox, Bivolt - CTG-01",
    "image": "https://m.media-amazon.com/images/I/517E2Ia2cWL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 349.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5575,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B085JFRRSW?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B07GWXBGYS",
    "title": "FISCHER COOKTOP GÁS 5 BOCAS TC INFINITY MESA INOX BIVOLT 23678-54121",
    "image": "https://m.media-amazon.com/images/I/71OM7XG9BbL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 979.9,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 2017,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B07GWXBGYS?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B7C9HXGL",
    "title": "Cooktop 4 Bocas Itatiaia Essencial com Mesa de Vidro Temperado e Acendimento Automático Preto Bivolt",
    "image": "https://m.media-amazon.com/images/I/71uLqItiKiL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 319.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1323,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0B7C9HXGL?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0G3Y8Y619",
    "title": "Máquina de Lavar Brastemp 14kg com Smart Sensor, Função Reduzir Tempo Branca BWJ14AB",
    "image": "https://m.media-amazon.com/images/I/612AvD2ZDrL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1965.16,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0G3Y8Y619?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0816YJYQB",
    "title": "SUGGAR DEPURADOR DE AR SLIM DE EMBUTIR 60CM INOX 220V DE62IX",
    "image": "https://m.media-amazon.com/images/I/51ciFDrjQLL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 769.9,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 980,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0816YJYQB?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 3599.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 517,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0B61WJRY5?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B09B8W3KQP",
    "title": "Máquina de Lavar Electrolux 15kg Branca Essential Care com Cesto Inox e Jet&Clean (LED15) - 127V",
    "image": "https://m.media-amazon.com/images/I/41pS08Q7EoL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 2039.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 857,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B09B8W3KQP?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BTZBQDMC",
    "title": "Suporte C/Rodinhas Base Ajustável Máquina Lavar Fogão Geladeira Móveis Resistente Reforçado",
    "image": "https://m.media-amazon.com/images/I/41ARppGGJyL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 32.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.3,
    "qtd_avaliacoes": 2812,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0BTZBQDMC?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FJJ3YY9B",
    "title": "Frigobar 93 Litros Inverter Bivolt Branco, Midea",
    "image": "https://m.media-amazon.com/images/I/31FoIRrnzXL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 949.26,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 285,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0FJJ3YY9B?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B07Q6LVF9J",
    "title": "Secadora de Roupa Mueller Solaris 8Kg 220V",
    "image": "https://m.media-amazon.com/images/I/513006cv6ZL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 509.9,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 286,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B07Q6LVF9J?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FK163DY6",
    "title": "Freezer Horizontal 100L Inverter Bivolt Branco Midea",
    "image": "https://m.media-amazon.com/images/I/41GOo1UPNmL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1199.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 59,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0FK163DY6?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B09KYJBZHS",
    "title": "Colormaq Maquina de Lavar Roupa Semi Automatica Tanquinho 20kg LCS20 Branco 220v",
    "image": "https://m.media-amazon.com/images/I/31LUQaj88JL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 609.99,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2401,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B09KYJBZHS?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BVNK3QD5",
    "title": "SUGGAR CENTRIFUGA DE ROUPAS GIROMAX 15KG PRATA 110V CT1501PR",
    "image": "https://m.media-amazon.com/images/I/51UqUIMQMDL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 443.33,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.4,
    "qtd_avaliacoes": 406,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0BVNK3QD5?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B3SHRP7S",
    "title": "SUGGAR DEPURADOR COIFA DE AR SLIM 80CM INOX 110V DPS181IX",
    "image": "https://m.media-amazon.com/images/I/41NHJDKA3XL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 509.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 1324,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0B3SHRP7S?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FVPMV5D8",
    "title": "Electrolux Fogão 4 bocas Electrolux Preto Efficient Mesa Vidro, Tripla Chama e PerfectCook (FE4GB) Bivolt",
    "image": "https://m.media-amazon.com/images/I/61CZYp8rp8L._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1549.0,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 98,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/dp/B0FVPMV5D8?tag=mixdm22-20",
    "last_checked_at": "2026-07-20T20:14:01.000Z",
    "spotlight": false
  }
];
