const PRODUCTS = [
  {
    "asin": "index-0",
    "title": "Frigobar Eos 71 Litros Ice Compact Branco Efb80 220v",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41W+miLnA1L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 697.54,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 2,
    "coupon_code": null,
    "description": "<ul><li>Classificação Energética/Inmetro A</li><li>Garantia do Compressor 10 anos</li><li>Degelo Manual</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "47P x 44,9L x 67,6A centímetros",
      "Marca": "EOS",
      "Capacidade": "76 litros",
      "Configuração": "Congelador interno compacto",
      "Cor": "branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Compact-Branco-Efb80/dp/B0GQC5GM8M/ref=zg_bs_g_16745429011_d_sccl_1/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": true
  },
  {
    "asin": "index-1",
    "title": "Frigobar 45 Litros Inverter Bivolt Branco",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31d6VuVOqQL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 599.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 20,
    "coupon_code": null,
    "description": "<ul><li>Tecnologia Inverter - Resfriamento rápido, garante a estabilidade da temperatura, preservando os alimentos por mais tempo, contribui para uma maior economia de energia com baixo nível de ruído.</li><li>Flexi Volt - Funciona tanto em 127V quanto em 220V, garantindo segurança e liberdade para usar em qualquer tomada.</li><li>Design Compacto - No tamanho ideal para qualquer ambiente, é espaçoso e funcional. Seus 45L acomodam facilmente bebidas, alimentos e até garrafas de 2 litros.</li><li>Compartimento Extra frio - Bebidas geladas mais rápido, com praticidade e conveniência, sempre que você precisar.</li><li>Compartimento de Latas - Mais organização e otimização do espaço interno com o compartimento para latas.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "45,5P x 47,2L x 49,2A centímetros",
      "Marca": "Midea",
      "Capacidade": "45 litros",
      "Cor": "branco",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Inverter-Bivolt-Branco/dp/B0GJG36MCZ/ref=zg_bs_g_16745429011_d_sccl_2/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": true
  },
  {
    "asin": "index-11",
    "title": "Frigobar Brastemp Retrô 76 Litros Classic White - BRA08MB (110, Volts)",
    "image": "https://images-na.ssl-images-amazon.com/images/I/5145MQyMlBL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": null,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 2,
    "coupon_code": null,
    "description": "<ul><li>O Frigobar Brastemp Retrô 76L economiza até 21% de energia¹. Design vintage com pés palito, 8 cores exclusivas e o icônico logo anos 50.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "55P x 48L x 82A centímetros",
      "Marca": "Brastemp",
      "Capacidade": "76 litros",
      "Cor": "branco",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Brastemp-Retr%C3%B4-Litros-Classic/dp/B0GQZFF9VC/ref=zg_bs_g_16745429011_d_sccl_12/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": true
  },
  {
    "asin": "index-12",
    "title": "Frigobar Brastemp Retrô 76 Litros Classic Black - BRA08ME (110, Volts)",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51aB+FU2oFL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 1784.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 5,
    "coupon_code": null,
    "description": "<ul><li>O Frigobar Brastemp Retrô 76L economiza até 21% de energia¹. Design vintage com pés palito, 8 cores exclusivas e o icônico logo anos 50.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "55P x 48L x 82A centímetros",
      "Marca": "Brastemp",
      "Capacidade": "76 litros",
      "Cor": "preto",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Brastemp-Retr%C3%B4-Litros-Classic/dp/B0GR18BSVR/ref=zg_bs_g_16745429011_d_sccl_13/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-17",
    "title": "Frigobar, 45L, Branco, 110V, Midea",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31ZcsTeNcuL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 719.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4236,
    "coupon_code": null,
    "description": "<ul><li>[Compartimento Gela Rápido] Espaço que acelera o resfriamento de seus alimentos e bebidas</li><li>[Compartimentos Adequados] Supercompacto com espaço otimizado, com espaço para garrafa 2L</li><li>[Considerar Design] 45L de capacidade, dimensões de 45,0 x 47,2 x 49,2 cm. É perfeito para dormitórios universitários, escritórios, garagens e pequenos apartamentos</li><li>[Termostato Ajustável] O controle da temperatura pode ser ajustado para melhor atender as condições de conservação dos alimentos, conforme o grau de utilização do aparelho</li><li>[Economia de Energia] Selo Procel e classificação “A” no Programa Brasileiro de Etiquetagem(PBE), mais economia para o seu bolso</li><li>[Componentes Incluídos] Frigobar e manual do usuário e garantia de 1 ano</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "52P x 52L x 46,5A centímetros",
      "Marca": "Midea",
      "Capacidade": "45 litros",
      "Configuração": "Frigobar, Termostato",
      "Cor": "Branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Midea-127V-MRC06B1-Branco/dp/B0778TZGBJ/ref=zg_bs_g_16745429011_d_sccl_18/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-22",
    "title": "Frigobar Eos Ice Compact 124l Efb131p Preto 110v",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41ayr0A4gwL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 1103.94,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 99,
    "coupon_code": null,
    "description": "<ul><li>Mais espaço 124 litros</li><li>Eco-Friendly</li><li>Termostato</li><li>Compartimento Gela Rápido</li><li>Degelo Manual</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "56P x 49,5L x 84A centímetros",
      "Marca": "EOS",
      "Capacidade": "124 litros",
      "Configuração": "Compacto",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Compact-124l-Efb131p-Preto/dp/B0C9VQ3R6V/ref=zg_bs_g_16745429011_d_sccl_23/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-24",
    "title": "Geladeira Portátil Preta 55 Litros Freezer Quadrivolt 12v/24v 110v/220v para Caminhão Ônibus Van Carro com Conexão Bluetooth",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51UO5O6u8OL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 1709.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>IDEAL PARA CAMINHÃO 12V/24V – Funciona direto na bateria ou tomada (110V/220V), perfeita para viagens longas, motorhome e uso diário na estrada</li><li>GELA E CONGELA DE VERDADE (-20°C) – Não é cooler: refrigeração real que mantém bebidas geladas e conserva carnes e congelados com eficiência</li><li>BAIXO CONSUMO COM PROTEÇÃO DE BATERIA – Modos ECO e MAX + sistema inteligente que evita descarregar a bateria do veículo</li><li>CONTROLE PELO CELULAR (BLUETOOTH) – Ajuste temperatura e funções pelo app, com painel digital e memória automática</li><li>GRANDE CAPACIDADE 55L + 2 COMPARTIMENTOS – Espaço interno otimizado com cesto removível, luz LED e organização prática para alimentos e bebidas</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "71P x 40L x 50A centímetros",
      "Marca": "Maxfreeze",
      "Capacidade": "55 litros",
      "Configuração": "Portable",
      "Cor": "preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Geladeira-Port%C3%A1til-Quadrivolt-Caminh%C3%A3o-Bluetooth/dp/B0GRX2LDYW/ref=zg_bs_g_16745429011_d_sccl_25/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-40",
    "title": "Frigobar 45L Midea",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81hC7IQpUgL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": null,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 231,
    "coupon_code": null,
    "description": "<ul><li>[Compartimento Gela Rápido] Espaço que acelera o resfriamento de seus alimentos e bebidas</li><li>[Compartimentos Adequados] Supercompacto com espaço otimizado, com espaço para garrafa 2L</li><li>[Considerar Design] 45L de capacidade, dimensões de 45,0 x 47,2 x 49,2 cm. É perfeito para dormitórios universitários, escritórios, garagens e pequenos apartamentos</li><li>[Termostato ajustável] O controle da temperatura pode ser ajustado para melhor atender as condições de conservação dos alimentos, conforme o grau de utilização do aparelho</li><li>[Economia de Energia] Selo Procel e classificação “A” no Programa Brasileiro de Etiquetagem(PBE), mais economia para o seu bolso</li><li>[Componentes Incluídos] Frigobar e manual do usuário e garantia de 1 ano</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Frigobar-45L-INOX-127V-Midea/dp/B0937J2WBG/ref=zg_bs_g_16745429011_d_sccl_41/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-48",
    "title": "Frigobar 70L Elgin - Porta Reversível Compartimento Extra Frio Branco 110V",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31aaazEcsPL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": null,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 20,
    "coupon_code": null,
    "description": "<ul><li>Porta reversível 180°;</li><li>Termostato com 7 níveis de ajuste;</li><li>Prateleiras de vidro removíveis;</li><li>Compartimento extra frio;</li><li>Compartimento para latas;</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "48,5P x 45,5L x 50,9A centímetros",
      "Marca": "Elgin",
      "Capacidade": "70 litros",
      "Configuração": "Congelador na parte inferior",
      "Cor": "branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-70L-Elgin-Revers%C3%ADvel-Compartimento/dp/B0FNY36KPD/ref=zg_bs_g_16745429011_d_sccl_49/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  },
  {
    "asin": "index-49",
    "title": "Frigobar 45 Litros Inverter Bivolt Preto com cor Prata",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61n52lD2MJL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 749.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Tecnologia Inverter - Resfriamento rápido, garante a estabilidade da temperatura, preservando os alimentos por mais tempo, contribui para uma maior economia de energia com baixo nível de ruído.</li><li>Flexi Volt - Funciona tanto em 127V quanto em 220V, garantindo segurança e liberdade para usar em qualquer tomada.</li><li>Design Compacto - No tamanho ideal para qualquer ambiente, é espaçoso e funcional. Seus 45L acomodam facilmente bebidas, alimentos e até garrafas de 2 litros.</li><li>Compartimento Extra frio - Bebidas geladas mais rápido, com praticidade e conveniência, sempre que você precisar.</li><li>Compartimento de Latas - Mais organização e otimização do espaço interno com o compartimento para latas.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "45,5P x 47,2L x 49,2A centímetros",
      "Marca": "Midea",
      "Capacidade": "45 litros",
      "Cor": "Prata",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Inverter-Bivolt-Preto/dp/B0GJFGN88Z/ref=zg_bs_g_16745429011_d_sccl_50/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-16T21:33:45.000Z",
    "spotlight": false
  }
];
