const PRODUCTS = [
  {
    "asin": "B0C5DXJ165",
    "title": "Placa de Video Gigabyte RX 7600 Gaming OC, 8gb, GDDR6 - GV-R76GAMING-OC-8GD",
    "image": "https://m.media-amazon.com/images/I/71U03CcRZzL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1699.99,
    "price_original": 1952.93,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 452,
    "coupon_code": null,
    "description": "<ul><li>GPU GIGABYTE AMD RADEON</li><li>RX 7600 GAMING</li><li>8GB 128BITS GDDR6</li><li>GIGABYTE</li></ul>",
    "informacoes_produto": {
      "Coprocessador gráfico": "AMD Radeon RX 7600",
      "Marca": "GIGABYTE",
      "Tamanho da memória RAM da placa gráfica": "8.0",
      "Velocidade do clock da GPU": "2805 MHz",
      "Interface de saída de vídeo": "DisplayPort"
    },
    "affiliate_url": "https://www.amazon.com.br/Placa-Video-Gigabyte-Gaming-GDDR6/dp/B0C5DXJ165?ref=dlx_deals_dg_dcl_B0C5DXJ165_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0918FHY6P",
    "title": "L'Oréal Professionnel Óleo 10 em 1 Absolut Repair | Multi-benefícios para cabelos secos e danificados | Repara e Promove Brilho | Com Gold Quinoa e Proteínas",
    "image": "https://m.media-amazon.com/images/I/61wfwHNv-NL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 123.39,
    "price_original": 247.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 22670,
    "coupon_code": null,
    "description": "<ul><li>Óleo de tratamento leave-in multibenefícios 10 em 1, que oferece nutrição, reparação instantânea e brilho para os fios</li><li>Sua fórmula profissional é enriquecida com Proteína do Trigo, garantindo uma restauração profunda e cabelos mais resistentes</li><li>Proporciona maciez e maleabilidade com um toque leve, sem pesar, facilitando o cuidado diário</li><li>Oferece proteção térmica e contra agressões externas, mantendo os cabelos saudáveis e protegidos no dia a dia</li><li>Repara a fibra capilar danificada, devolvendo a suavidade e o brilho para um resultado de salão instantâneo em casa</li></ul>",
    "informacoes_produto": {
      "Tipo de cabelo": "Fino",
      "Tipo de material livre": "Sem conservantes",
      "Aroma": "Sem perfume",
      "Volume líquido": "1 Onças líquidas"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Multi-benef%C3%ADcios-danificados-Prote%C3%ADnas/dp/B0918FHY6P?ref=dlx_deals_dg_dcl_B0918FHY6P_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H4HYLQ71",
    "title": "Notebook Gamer Lenovo Loq 15irx9, 15.6\" Full Hd 144hz, Intel Core I5-13450hx, 16gb, 512gb Ssd, Nvidia Rtx 4050, Linux - 83khs00300",
    "image": "https://m.media-amazon.com/images/I/61+CippnCvL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 5899.0,
    "price_original": 6555.54,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 5,
    "coupon_code": null,
    "description": "<ul><li>Processador estável Intel Core i5-13450HX</li><li>Tela Gamer com taxa de 144Hz</li><li>Notebook Gamer Lenovo LOQ 15IRX9 i5 16GB 512GB SSD RTX 4050 144Hz</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ 15IRX9",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "512 GB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Linux",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "49 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-15irx9-I5-13450hx-Nvidia/dp/B0H4HYLQ71?ref=dlx_deals_dg_dcl_B0H4HYLQ71_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "B07VRYJWPB",
    "title": "Finish Power Powder Advanced Detergente para Lava Louças em Pó 2,5kg",
    "image": "https://m.media-amazon.com/images/I/61FuIlOh2GL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 98.78,
    "price_original": 146.59,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 22479,
    "coupon_code": null,
    "description": "<ul><li>Finish Power Powder Advanced é o seu detergente lava louças em pó que oferece limpeza profunda na dose certa. Recomendado pelos principais fabricantes de lava louças do Brasil e do mundo.</li><li>Sua louça do dia a dia vai ficar limpa de primeira, sem necessidade de pré-enxague. Possui ingredientes na fórmula que promovem o cuidado e proteção das louças.</li><li>Exclusiva fórmula com oxigênio ativo e enzimas que promovem limpeza através de sua ação desengordurante e da remoção de sujeiras.</li><li>Vem com medidor que ajuda a dosar corretamente a quantidade do detergente lava louças.</li><li>Usar lava louças remove até as sujeiras mais difíceis, sem bagunça, sem ressecar as mãos. É mais qualidade de vida!</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Pó",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "4"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergente-Para-Lou%C3%A7as-Finish-Advanced/dp/B07VRYJWPB?ref=dlx_deals_dg_dcl_B07VRYJWPB_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DYVNRG3B",
    "title": "Celular Samsung Galaxy A36 5G 128GB, 6GB RAM, Câmera 50MP, IP67, Super AMOLED 6.7\", Recursos AI, Branco",
    "image": "https://m.media-amazon.com/images/I/613Vrz+GcaL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1449.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2470,
    "coupon_code": null,
    "description": "<ul><li>Feito para Durar: até 6 atualizações de Android e Segurança</li><li>Tela imersiva de 6.7\" Super AMOLED com Vision Booster</li><li>Resistente à água e poeira com IP67</li><li>Câmera com recursos de AI e Nightography / Circule para Pesquisar no Google</li><li>Bateria de 5000 mAh e carregamento rápido de até 45W</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Sistema operacional": "Android 15.0",
      "Tamanho instalado da memória RAM": "6 GB",
      "Modelo da CPU": "A-Series",
      "Velocidade da CPU": "2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Celular-Samsung-Galaxy-C%C3%A2mera-Recursos/dp/B0DYVNRG3B?ref=dlx_deals_dg_dcl_B0DYVNRG3B_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "B0GL3YFDQ9",
    "title": "Samsung Ar Condicionado Split Inverter Samsung WindFree AI 24000 BTU/h Frio AR60F24D1AWNAZ - 220 Volts",
    "image": "https://m.media-amazon.com/images/I/51HhpshEOKL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3599.0,
    "price_original": 4419.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Tipo de Produto: Ar Condicionado Split com tecnologia Inverter da marca Samsung</li><li>Capacidade de Refrigeração: Sistema com 24000 BTU/h que proporciona climatização eficiente para ambientes amplos</li><li>Tecnologia WindFree: Modo sem vento que dispersa o ar através de 23.000 microfuros, eliminando o vento gelado direto e proporcionando maior conforto</li><li>Inteligência Artificial: Sistema AI que aprende as preferências do usuário e compara com temperaturas interna e externa para climatização automática e economia de energia</li><li>Conectividade Inteligente: Controle via WiFi através do app SmartThings com compatibilidade para comandos de voz por Bixby, Alexa e Google Assistente</li><li>Eficiência Energética: Classificação A no Inmetro com economia de até 77% de energia e monitoramento de consumo em tempo real</li><li>Modo Welcome Cooling: Climatização automática que detecta sua localização via smartphone e liga o aparelho quando você se aproxima de casa</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Capacidade": "2 tons",
      "Dimensões do produto": "38P x 111L x 30A centímetros",
      "Cor": "Branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Condicionado-Inverter-WindFree-AR60F24D1AWNAZ/dp/B0GL3YFDQ9?ref=dlx_deals_dg_dcl_B0GL3YFDQ9_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "B099KTRZP7",
    "title": "Fralda Turma da Mônica Baby Mega P 62 Unidades",
    "image": "https://m.media-amazon.com/images/I/61GqSAiDmHL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 33.01,
    "price_original": 50.04,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 48142,
    "coupon_code": null,
    "description": "<ul><li>Nova tecnologia Qu4troSec, a fralda que segura bem: absorve e não vaza</li><li>Cintura elástica, que proporciona perfeito ajuste no corpinho do bebê</li><li>Sistema de canais super absorventes que distribuem mais rápido o xixi</li><li>Fina camada extra que deixa seu bebê sequinho por até 12 horas</li><li>Barreiras anti-vazamento</li></ul>",
    "informacoes_produto": {
      "Marca": "Turma da Mônica",
      "Número de itens": "1",
      "Cor": "Azul",
      "Tipo de protetor de incontinência": "Fralda infantil",
      "Faixa etária (descrição)": "Bebê"
    },
    "affiliate_url": "https://www.amazon.com.br/Fralda-Turma-Baby-Unidades-M%C3%B4nica/dp/B099KTRZP7?ref=dlx_deals_dg_dcl_B099KTRZP7_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GM1LSHQF",
    "title": "JBL, Fone de Ouvido Bluetooth Over-Ear, Tune 530BT, Sem Fio, Até 76 Horas de Bateria - Preto",
    "image": "https://m.media-amazon.com/images/I/61q9MOnS+2L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 199.0,
    "price_original": 299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-Ouvido-Bluetooth-Over-Ear-Bateria/dp/B0GM1LSHQF?ref=dlx_deals_dg_dcl_B0GM1LSHQF_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FJPL1MGY",
    "title": "Samsung Galaxy Watch Ultra 2025 Smartwatch 47mm LTE, Galaxy AI, Titânio Aeroespacial, Titânio Prata",
    "image": "https://m.media-amazon.com/images/I/518YXVYcCRL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 2099.0,
    "price_original": 4999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 66,
    "coupon_code": null,
    "description": "<ul><li>Titânio Aeroespacial e resistência</li><li>Até 100m de resistencia a água do mar</li><li>Bateria de até 100h</li><li>GPS duplo de alta precisão</li><li>Treinador de corrida avançado</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "Galaxy AI",
      "Capacidade de armazenamento da memória": "64 GB",
      "Capacidade da bateria": "590 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, NFC, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Galaxy-Watch-Smartwatch-Tit%C3%A2nio/dp/B0FJPL1MGY?ref=dlx_deals_dg_dcl_B0FJPL1MGY_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "B0G3CY35DN",
    "title": "Notebook Lenovo IdeaPad Slim 3 15IRU10 Intel Core 3 100U 8GB 256GB SSD Windows 11 15.3\" - 83NU0000BR Luna Grey",
    "image": "https://m.media-amazon.com/images/I/61QqrCnGyfL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3399.0,
    "price_original": 1299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 7,
    "coupon_code": null,
    "description": "<ul><li>Aumente sua produtividade e mobilidade com o IdeaPad Slim 3i</li><li>Tela IPS de 16\" WUXGA (16:10) com imagens nítidas e cores vibrantes</li><li>Gráficos Intel Arc para performance avançada em tarefas criativas</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "IdeaPad Slim 3 15IRU10",
      "Tamanho da tela": "15,3 Polegadas",
      "Cor": "Cinza",
      "Tamanho do disco rígido": "256 GB",
      "Modelo da CPU": "Intel Core 3",
      "Tamanho instalado da memória RAM": "8 GB",
      "Sistema operacional": "Windows 11 Home Single Language",
      "Características especiais": "Áudio HD",
      "Descrição da placa de vídeo": "Integrated Intel Graphics"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-IdeaPad-15IRU10-Windows/dp/B0G3CY35DN?ref=dlx_deals_dg_dcl_B0G3CY35DN_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GND7R7Z8",
    "title": "Ar Condicionado Split Hi Wall LG Dual Voice AI Inverter 24.000 Btus Frio 220v R-32",
    "image": "https://m.media-amazon.com/images/I/51XtHBetEOL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 3899.0,
    "price_original": 4299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 3,
    "coupon_code": null,
    "description": "<ul><li>Comando de Voz AI</li><li>Wi-Fi ThinQ Integrado</li><li>Economia Energia 70%</li><li>Refrigeração Rápida 40%</li><li>Dual Inverter AI</li></ul>",
    "informacoes_produto": {
      "Marca": "LG",
      "Capacidade": "43 quilogramas",
      "Energia de resfriamento": "24000 BTUs",
      "Características especiais": "Controlado Remotamente, Activado por WiFi",
      "Dimensões do produto": "0,7P x 2L x 1A Metros"
    },
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Split-LG-Inverter-24-000/dp/B0GND7R7Z8?ref=dlx_deals_dg_dcl_B0GND7R7Z8_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BGMD5LGF",
    "title": "Personal Fralda Baby Premium Pants G, 62 Unidades",
    "image": "https://m.media-amazon.com/images/I/51YPzh4uhaL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 81.98,
    "price_original": 116.89,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 5145,
    "coupon_code": null,
    "description": "<ul><li>Fácil de vestir e fácil de tirar</li><li>Super Macio como Toque de Algodão*</li><li>Rápida Absorção 3D Ultrarrespirável - Até 12hrs de Proteção</li><li>Ajuste Perfeito Não Aperta Barriguinha e Perninhas</li><li>Tecnologia Japonesa</li></ul>",
    "informacoes_produto": {
      "Marca": "Personal",
      "Número de itens": "62",
      "Cor": "Branco",
      "Tipo de protetor de incontinência": "Fralda infantil",
      "Faixa etária (descrição)": "Bebê"
    },
    "affiliate_url": "https://www.amazon.com.br/Fralda-Personal-Baby-Premium-Pants/dp/B0BGMD5LGF?ref=dlx_deals_dg_dcl_B0BGMD5LGF_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FPRK5P9H",
    "title": "SEMP, Smart TV 4K UHD, 55“, Google TV, Google Assistente, Comando por Voz, Googlecast Integrado, Design Sem Bordas, Dolby Audio, 55S62",
    "image": "https://m.media-amazon.com/images/I/61mUtpPKNVL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 2099.99,
    "price_original": 2499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 166,
    "coupon_code": null,
    "description": "<ul><li>Smart TV com Google TV, Wi-Fi Dual Band, Bluetooth, Google Assistente, Dolby Audio, HDMI 2.1, HDR10+ e Googlecast Integrado</li><li>Tela 4K UHD de 55 polegadas com design sem bordas na cor preta, proporcionando imagem de alta resolução e visual moderno</li><li>Controle por comando de voz via Google Assistente para navegação prática entre aplicativos, conteúdos e configurações da TV</li></ul>",
    "informacoes_produto": {
      "Tamanho da tela": "55",
      "Marca": "Semp",
      "Tecnologia do visor": "4K UHD, LCD, OLED, UHD",
      "Resolução": "4K",
      "Taxa de atualização": "60 Hz",
      "Características especiais": "Google Assistente, Dolby Audio, HDMI 2.1, HDR10+, Googlecast Integrado, design sem bordas",
      "Componentes incluídos": "01 Televisor 55\", 01 Controle Remoto, 1 Cabo Adaptador P2/RCA",
      "Tecnologia de conectividade": "HDMI, USB, Wi-fi",
      "Proporção de tela": "16:9",
      "Dimensões do produto": "71,1P x 122,6L x 7,3A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SEMP-SMART-55S62-UHD-GOOGLE/dp/B0FPRK5P9H?ref=dlx_deals_dg_dcl_B0FPRK5P9H_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B07FPW95CM",
    "title": "Jameson - Whiskey Irlandês, 750 ml",
    "image": "https://m.media-amazon.com/images/I/51syfbaTceL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 69.08,
    "price_original": 130.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7085,
    "coupon_code": null,
    "description": "<ul><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li></ul>",
    "informacoes_produto": {
      "Marca": "Jameson",
      "Tipo de álcool": "Blended whiskey",
      "Sabor": "Whisky",
      "Número de itens": "1",
      "Teor alcoólico": "15 %"
    },
    "affiliate_url": "https://www.amazon.com.br/Jameson-Whisky-750ml/dp/B07FPW95CM?ref=dlx_deals_dg_dcl_B07FPW95CM_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FL2QF7YJ",
    "title": "JBL, Caixa de Som, PartyBox Encore Essential 2, Show de Luzes, Bluetooth, Portátil, Resistente a Respingos, Bateria de até 15h, Som JBL Pro Sound, AI Sound Boost, 100 W RMS",
    "image": "https://m.media-amazon.com/images/I/71Ar78y955L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1328.99,
    "price_original": 1899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 459,
    "coupon_code": null,
    "description": "<ul><li>SOM POTENTE COM AI SOUND BOOST. O JBL Pro Sound ganha ainda mais potência com o AI Sound Boost, oferecendo agudos nítidos e graves impactantes, mesmo em alto volume e ambientes amplos.</li><li>SHOW DE LUZES NO RITMO DA MÚSICA. Os efeitos de luzes dinâmicas criam o clima ideal para qualquer festa, com padrões vibrantes e estroboscópicos que seguem o ritmo da sua playlist do começo ao fim.</li><li>DURAÇÃO PARA O DIA TODO. A bateria integrada oferece até 15 horas de reprodução contínua com uma única carga.</li><li>TECNOLOGIA AURACAST. É possível emparelhar com outro JBL PartyBox Encore Essential 2 ou conectar várias caixas via JBL Auracast para ampliar sua experiência sonora.</li><li>DESIGN RESISTENTE. Com alça prática para transporte e proteção contra respingos (IPX4), a PartyBox Encore Essential 2 está pronta para festas em qualquer ambiente ou clima.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Dimensões do item C x L x A": "29 x 33 x 28 centímetros",
      "Tecnologia de conectividade": "Bluetooth",
      "Cor": "Preto",
      "Dispositivos compatíveis": "Leitor de MP3, Notebook, Smartphone, Tablet"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-PartyBox-Essential-Bluetooth-Respingos/dp/B0FL2QF7YJ?ref=dlx_deals_dg_dcl_B0FL2QF7YJ_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B07X4JG2G4",
    "title": "Duracell Carregador de Pilhas Recarregáveis AA e AAA Com 4 Pilhas AA Inclusas – Bivolt",
    "image": "https://m.media-amazon.com/images/I/819KK4qPMeL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 144.3,
    "price_original": 198.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 62227,
    "coupon_code": null,
    "description": "<ul><li>Auto desligamento quando as pilhas carregam 100%</li><li>Proteção que garante o carregamento seguro</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "2500",
      "Adequação do controle por rádio": "Aparelho auditivo, Controle remoto da TV, Câmera, Drone, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Carregador-Pilhas-com-pilhas-Duracell/dp/B07X4JG2G4?ref=dlx_deals_dg_dcl_B07X4JG2G4_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "B09LHWJF1F",
    "title": "Forno de Embutir Oster Elétrico, 77L, Black, 220V, OFOR7740",
    "image": "https://m.media-amazon.com/images/I/414Xyz+L2FL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Oferas do dia",
    "price_current": 1454.53,
    "price_original": 2199.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 26,
    "coupon_code": null,
    "description": "<ul><li>CONFIRA AS MEDIDAS IDEIAS PARA INSTALAR ESTE FORNO NA SUA COZINHA E A VOLTAGEM DO PRODUTO: Medidas correspondentes ao nicho para embutir o produto. Veja mais informações no manual.</li><li>GRANDE NA CAPACIDADE E ENORME NA BELEZA: Com o tamanho de 77 litros, você vai poder preparar diferentes tipos de receitas: de sobremesas a assados.</li><li>FUNÇÕES PRÉ-PROGRAMADAS: Programe o seu preparo com segurança, sabendo o horário que vai iniciar e terminar. Segurança, praticidade e eficiência.</li><li>AJUSTE DE ALTURA E BANDEJA COLETORA: Posicione a grade de acordo com o resultado desejado. A bandeja coletora garante facilidade para a limpeza.</li><li>TIMER DE ATÉ 120 MINUTOS: Você pode programar o preparo de receitas mais longas por até 120 minutos sem interrupções.</li></ul>",
    "informacoes_produto": {
      "Tamanho": "29,55 Kg",
      "Marca": "Oster",
      "Cor": "preto",
      "Método de aquecimento": "Convecção",
      "Tipo de acabamento": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Forno-Embutir-El%C3%A9trico-Oster-Black/dp/B09LHWJF1F?ref=dlx_deals_dg_dcl_B09LHWJF1F_dt_sl14_88_pi&pf_rd_r=T4144XAWEDAD12KBKH16&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "index-0",
    "title": "Pilha Alcalina, Elgin, Palito AAA, Blister com 4",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71faB-DYcoL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 6.66,
    "price_original": 11.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 31653,
    "coupon_code": null,
    "description": "<ul><li>Embalagem com 4 pilhas alcalinas tipo AAA Palito</li><li>Alta Durabilidade na Carga.</li><li>Composição livre de metais pesados que são prejudiciais à saúde.</li><li>Aprovadas por laboratórios credenciados pelo INMETRO.</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>As alcalinas AAA da Elgin receberam os selos Melhor do Teste e Escolha Certa da Proteste de pilhas com melhor desempenho.</li><li>Validade 5 anos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "300 Amperes Horas",
      "Adequação do controle por rádio": "Diversos"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilhas-Alcalinas-Palito-Elgin-Baterias/dp/B0754J12RW/ref=zg_bs_g_electronics_d_sccl_1/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-4",
    "title": "Pilha recarregável AAA 1000mAh Elgin com 4 unidades Palito",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71SnHLZ+XjL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 22.25,
    "price_original": 43.02,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 23240,
    "coupon_code": null,
    "description": "<ul><li>Blister Com 4 Pilhas AAA de 1000Mah.</li><li>Energia renovável de alta qualidade, as pilhas recarregáveis da Elgin suportam até 1000 recargas.</li><li>Aprovadas pelo INMETRO: As Pilhas Elgin Energy são testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Indicada para brinquedos, controle de videogames e produtos de alto consumo de pilha.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "NiMH",
      "Capacidade da bateria": "1000",
      "Adequação do controle por rádio": "Brinquedos"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-recarreg%C3%A1vel-1000mAh-unidades-Palito/dp/B0754KMGFN/ref=zg_bs_g_electronics_d_sccl_5/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-6",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina de lavar, reutilizáveis",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61BJhE0GLIL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 19.9,
    "price_original": 25.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4320,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Material": "Plástico, Poliéster",
      "Cor": "Branco",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros",
      "Características especiais": "Acabamento no zíper, Fácil de limpar"
    },
    "affiliate_url": "https://www.amazon.com.br/Oikos-conjunto-m%C3%A1quina-roupas-delicadas/dp/B086WWQX1S/ref=zg_bs_g_appliances_d_sccl_7/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-8",
    "title": "Roku Streaming Stick HD 2025 | Dispositivo de streaming para TV HD/FHD com controle remoto por comando de voz compatível com Alexa, Siri e Google",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71NIAAVDxML._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 245.56,
    "price_original": 289.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 3516,
    "coupon_code": null,
    "description": "<ul><li>Streaming simplificado: com a plataforma de streaming para TV nº 1 dos Estados Unidos*, é fácil e divertido descobrir apps populares, além de milhares de filmes, séries, esportes e TV ao vivo. *Baseado em horas de streaming—Hypothesis Group</li><li>Transforme sua TV em uma Smart TV de verdade com o Roku Streaming Stick.</li><li>O design compacto do Roku Streaming Stick não bloqueia as entradas HDMI vizinhas e pode ser alimentado pela porta USB da sua TV. Ele se conecta diretamente à parte de trás da sua TV e fica super discreto. Sem tomada, sem cabos extras, sem bagunça.</li><li>Chega de usar vários controles remotos: ligue a TV, ajuste o volume e controle o dispositivo Roku com um controle remoto. Use a voz para pesquisar rápido, assistir ao seu conteúdo favorito e muito mais.</li><li>Leve sua TV favorita com você: com o design portátil desse dispositivo de streaming, você pode levar sua TV na mala quando estiver viajando, sem precisar fazer login no dispositivo de outra pessoa.</li><li>Todos os principais apps: você não vai mais precisar perguntar “Onde está passando?\". Agora todos os principais apps estão em um só lugar, para que você possa sempre fazer streaming dos seus programas de TV, filmes favoritos e muito mais.</li><li>Fácil de usar: comece imediatamente com uma tela inicial que dá acesso ao que você quer assistir de forma rápida.</li><li>TV ao vivo gratuita de verdade: aproveite dezenas de canais com notícias ao vivo, esportes, dramas e muito mais - tudo isso totalmente de graça.</li><li>Configuração rápida e fácil: basta ligar seu dispositivo, conectar-se à internet e mergulhar em um mundo de streaming.</li></ul>",
    "informacoes_produto": {
      "Marca": "Roku",
      "Tecnologia de conectividade": "Wi-fi",
      "Tipo de conector": "HDMI",
      "Características especiais": "Compatível com Apple AirPlay e HomeKit, Compatível com Google Home, Compatível com Alexa",
      "Resolução": "1080p"
    },
    "affiliate_url": "https://www.amazon.com.br/Roku-Streaming-Dispositivo-streaming-compat%C3%ADvel/dp/B0FH7LY3R4/ref=zg_bs_g_electronics_d_sccl_9/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-9",
    "title": "Smartwatch Samsung Galaxy Fit3 Display 1.6\" Grafite",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51bjAlTBzZL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 221.11,
    "price_original": 599.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11970,
    "coupon_code": null,
    "description": "<ul><li>Para começar a usar o Galaxy Fit3, uma conta Samsung deve estar cadastrada em seu celular. Seus dados de saúde no seu Galaxy Fit3 serão transferidos com segurança e armazenados na Samsung Cloud conectada à sua conta, para que você possa acessar e gerenciar totalmente seus dados.</li><li>Quando a bateria estiver completamente descarregada, o Fit não ligará. Carregue totalmente o bateria antes de ligar o Fit.</li><li>A tela sensível ao toque pode funcionar mal em condições úmidas ou quando exposta à água.</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "FreeRTOS",
      "Capacidade de armazenamento da memória": "16 MB",
      "Características especiais": "Leve",
      "Capacidade da bateria": "3000 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartwatch-Samsung-Galaxy-Display-Grafite/dp/B0CVCLGV1W/ref=zg_bs_g_electronics_d_sccl_10/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-11",
    "title": "Refil Filtro Vela Purificador Soft Everest Original",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41XhFbEHcKL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 90.49,
    "price_original": 850.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1073,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {
      "Material": "Carvão",
      "Dimensões do produto": "12P x 30L x 8A centímetros",
      "Peso do produto": "600 Gramas",
      "Vantagens do produto": "Remove impurezas e contaminantes",
      "Marca": "SOFT"
    },
    "affiliate_url": "https://www.amazon.com.br/Refil-Filtro-Purificador-Everest-Original/dp/B07CZ3R2P8/ref=zg_bs_g_appliances_d_sccl_12/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": true
  },
  {
    "asin": "index-16",
    "title": "Duracell Carregador de Pilhas Recarregáveis AA e AAA Com 4 Pilhas AA Inclusas – Bivolt",
    "image": "https://images-na.ssl-images-amazon.com/images/I/819KK4qPMeL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 144.3,
    "price_original": 198.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 62227,
    "coupon_code": null,
    "description": "<ul><li>Auto desligamento quando as pilhas carregam 100%</li><li>Proteção que garante o carregamento seguro</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "2500",
      "Adequação do controle por rádio": "Aparelho auditivo, Controle remoto da TV, Câmera, Drone, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Carregador-Pilhas-com-pilhas-Duracell/dp/B07X4JG2G4/ref=zg_bs_g_electronics_d_sccl_17/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-17",
    "title": "JBL, Fone de Ouvido Bluetooth Over-Ear, Tune 530BT, Sem Fio, Até 76 Horas de Bateria - Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61q9MOnS+2L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 199.0,
    "price_original": 299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-Ouvido-Bluetooth-Over-Ear-Bateria/dp/B0GM1LSHQF/ref=zg_bs_g_electronics_d_sccl_18/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-18",
    "title": "ELG, GENIUS, Suporte Fixo Universal de Parede Para TVs de 14” a 100”, Capacidade até 100 kg, Padrão VESA de 75x75 a 800x400mm, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41Ap3CmMlES._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 26.49,
    "price_original": 39.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 38800,
    "coupon_code": null,
    "description": "<ul><li>SUPORTE FIXO DE PAREDE: Construído com aço de alta resistência, o suporte GENIUS da ELG oferece segurança incomparável. Seu sistema de encaixe rápido e trava de segurança garantem praticidade na instalação e uso diário.</li><li>DURÁVEL E CONFIÁVEL: Com uma garantia total de 5 anos contra defeitos de fabricação ou em suas peças, o suporte GENIUS da ELG demonstra a confiança da marca em sua qualidade superior.</li><li>ACABAMENTO PREMIUM: O acabamento em pintura eletrostática não é apenas esteticamente agradável, mas também funcional. Esta tecnologia avançada proporciona maior durabilidade ao produto e resistência superior a riscos.</li><li>FÁCIL INSTALAÇÃO: Graças ao gabarito e kit de acessórios inclusos. Seja em parede de madeira ou alvenaria, você terá todas as ferramentas necessárias para uma montagem fácil e segura.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "ELG",
      "Material": "Aço carbono",
      "Cor": "PRETO"
    },
    "affiliate_url": "https://www.amazon.com.br/Suporte-Universal-Parede-Elg-GENIUS/dp/B0765P3DB8/ref=zg_bs_g_electronics_d_sccl_19/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-20",
    "title": "Britânia SANDUICHEIRA E GRILL PRESS 127V, BGR27I",
    "image": "https://images-na.ssl-images-amazon.com/images/I/5136pVcmWhL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 125.26,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11363,
    "coupon_code": null,
    "description": "<ul><li>Revestimento Dura Mais: Não deixam o alimento grudar, tem maior durabilidade e é fácil de limpa.</li><li>2 em 1 (Grill e Sanduicheira) : Prepare saborosos sanduíches, hambúrgueres , carnes, peixe, vegetais e muito mais.</li><li>Chapa superior Grill e chapa inferior lisa: Ideal para preparar diversas receitas.</li><li>Placa superior de aquecimento ajustável: Prepara alimentos de diversas espessuras sem amassar.</li><li>Compacta, prática e mais saudável: Não precisa usar óleo, proporcionando alimentos mais saudáveis.</li></ul>",
    "informacoes_produto": {
      "Cor": "Inox",
      "Material": "Plástico e Metal",
      "Marca": "Britânia",
      "Dimensões do produto": "22P x 26L x 8A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Brit%C3%A2nia-SANDUICHEIRA-GRILL-PRESS-BGR27I/dp/B09WWY48B7/ref=zg_bs_g_kitchen_d_sccl_21/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-21",
    "title": "Kit com 5 Potes de Vidro Gato Panda, 640 ml, Retangular, com Tampa Hermética, Azul",
    "image": "https://images-na.ssl-images-amazon.com/images/I/814oRtHfLLL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 59.9,
    "price_original": 99.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3941,
    "coupon_code": null,
    "description": "<ul><li>🔒 Potes de Vidro Hermético com Tampa 4 Travas e Silicone – Sistema de vedação hermética com anel de silicone removível que conserva alimentos por mais tempo. Ideal como pote de vidro com tampa para armazenamento seguro sem vazamentos.</li><li>🔥 Recipiente de Vidro 640ml para Micro-ondas, Forno e Freezer – Pote de vidro resistente a altas temperaturas (até 300°C), pode ir ao microondas, freezer e forno sem tampa. Perfeito para marmita de vidro e armazenamento térmico.</li><li>🌱 Pote de Vidro Livre de BPA para Armazenar Alimentos – Alternativa saudável aos potes plásticos. Não absorve odores, não mancha e mantém sabor original. Ideal para organização de cozinha e conservação de alimentos.</li><li>🍱 Kit 5 Potes de Vidro Retangular 640ml para Marmita e Meal Prep – Conjunto de recipientes de vidro herméticos para preparar marmitas, guardar arroz, feijão, massas, saladas e refeições prontas.</li><li>🧼 Organizador de Alimentos em Vidro Transparente Fácil de Limpar – Design empilhável, vidro durável e tampa desmontável que facilita higienização. Excelente para organização de geladeira, armário e despensa.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATO PANDA",
      "Cor": "Azul",
      "Material": "Vidro borossilicato",
      "Característica do material": "Seguro para forno, Seguro para micro-ondas, Sem BPA",
      "Capacidade": "640 ml"
    },
    "affiliate_url": "https://www.amazon.com.br/Potes-Vidro-Retangular-Tampa-Herm%C3%A9tica/dp/B08CPW5BR2/ref=zg_bs_g_kitchen_d_sccl_22/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-22",
    "title": "Brinox - Panela de Pressão 4,2L Antiaderente Ceramic Life com Fundo de Indução Pressure - Vanilla",
    "image": "https://images-na.ssl-images-amazon.com/images/I/515ty+4I4BL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 219.99,
    "price_original": 312.47,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 4348,
    "coupon_code": null,
    "description": "<ul><li>DIFERENCIAIS: A Panela de Pressão Brinox Ceramic Life Pressure com indução foi desenvolvida para agilizar o preparo das refeições do dia a dia. Com capacidade de 4,2 litros, oferece eficiência no cozimento, praticidade no uso e desempenho confiável para diferentes receitas.</li><li>MATERIAIS: O corpo da panela é produzido em alumínio, material que favorece a condução do calor e contribui para uma cocção mais rápida e uniforme. Os cabos e alças são fabricados em baquelite antitérmico, garantindo segurança no manuseio.</li><li>COMPOSIÇÃO: Possui revestimento interno antiaderente Ceramic Life, com classificação A (ótima) de antiaderência, facilitando o preparo dos alimentos e a limpeza. O sistema de pressão conta com três dispositivos de segurança: trava de segurança, válvula de trabalho e válvula de segurança.</li><li>INSTRUÇÕES DE USO E RECOMENDAÇÕES: Antes do primeiro uso, recomenda-se realizar a cura do revestimento. Após o preparo, evitar choques térmicos e efetuar a limpeza manual com esponja macia e detergente neutro, sem utilizar produtos abrasivos.</li><li>TIPOS DE FOGÕES: Compatível com fogões a gás, elétricos, vitrocerâmicos e por indução, graças ao fundo preparado para esse tipo de uso. Não deve ser utilizada em forno, micro-ondas ou lava-louças.</li><li>RESUMO: Funcional e prática, a Panela de Pressão Brinox Ceramic Life Pressure é indicada para o preparo de carnes, grãos, legumes e receitas que exigem cozimento sob pressão, oferecendo agilidade e desempenho no uso diário.</li></ul>",
    "informacoes_produto": {
      "Marca": "Brinox",
      "Capacidade": "4,2 litros",
      "Material": "Alumínio",
      "Cor": "Vanilla",
      "Tipo de acabamento": "Brilhante"
    },
    "affiliate_url": "https://www.amazon.com.br/Pressao-indu%C3%A7%C3%A3o-Pressure-BRINOX-REVESTIDOS/dp/B08YFLVSBP/ref=zg_bs_g_kitchen_d_sccl_23/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-23",
    "title": "Dolce Gusto Mochaccino Em Cápsula Avelã Nescafé Caixa 170G 10 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61-U7n6-0uL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 16.73,
    "price_original": 0.1,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 5813,
    "coupon_code": null,
    "description": "<ul><li>MÁQUINA NESCAFÉ DOLCE GUSTO: cápsulas para o sistema Nescafé Dolce Gusto. Conheça uma das mais de 35 opções de bebidas incríveis! As máquinas e cafeteiras Nescafé Dolce Gusto podem fazer em casa suas bebidas favoritas da cafeteria: basta apertar um botão!</li><li>MOCHACCINO AVELÃ: Um verdadeiro deleite! Você só precisa de uma xícara do Mochaccino Avelã para saborear um sabor que é puro conforto! É a magia do aroma de café e o toque de sabor avelã que vai fazer você se sentir abraçado! São 10 cápsulas para aproveitar e saborear.</li><li>MODO DE PREPARO: após preencher o recipiente da sua máquina Nescafé Dolce Gusto com água, coloque uma cápsula Nescafé Dolce Gusto Mochaccino Avelã, ajuste a quantidade de água sugerida, que são 4 níveis e ligue sua máquina no modo quente.</li><li>NOSSO COMPROMISSO COM O PLANETA: 100% do nosso café é certificado por parceiros especializados. Isso quer dizer que além de sabermos de onde vem cada xícara de café. Você sabia que é fácil reciclar suas cápsulas de Nescafé Dolce Gusto? Basta colocar as cápsulas usadas em um saco ou caixa de papelão para que não suje ou molhe os outros materiais recicláveis. E caso haja muito líquido nas cápsulas, você pode deixá-las escorrendo por um tempinho antes de descartá-las. Não é preciso lavá-las e nem retirar o conteúdo interno. Descarte em um lixo reciclável e suas cápsulas serão encaminhadas para uma cooperativa e após os processos sua cápsula ganha uma segunda vida e se tornará um novo objeto!</li></ul>",
    "informacoes_produto": {
      "Marca": "Nescafé Dolce Gusto",
      "Forma do produto": "Cápsula",
      "Sabor": "Avelã",
      "Descrição do teor de cafeína": "Com cafeína",
      "Nível de torragem": "Torra clara"
    },
    "affiliate_url": "https://www.amazon.com.br/Dolce-Mochaccino-C%C3%A1psula-Nescaf%C3%A9-Unidades/dp/B0CN1L7B18/ref=zg_bs_g_kitchen_d_sccl_24/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-25",
    "title": "Pilha Panasonic Comum AA c/04 unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61sfR1a-7eL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 17.0,
    "price_original": 17.99,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5598,
    "coupon_code": null,
    "description": "<ul><li>Excelente custo/benefício</li><li>Comum</li><li>Característica do produto: pequena</li><li>Voltagem: 1, 5V Conserto/ Troca: Troca</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA (necessita de baterias)",
      "Marca": "Panasonic",
      "Composição das células da bateria": "Alcalina",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "4.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Panasonic-UM-3SHS-PILHA-COMUM-AA/dp/B075XFDPL2/ref=zg_bs_g_electronics_d_sccl_26/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-28",
    "title": "Caixa de Pilha AAA com 40 unidades Elgin Palito - Tubo, Zinco",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51wlcSTwZsL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 28.7,
    "price_original": 0.72,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 7417,
    "coupon_code": null,
    "description": "<ul><li>Caixa com 40 pilhas de zinco AAA Palito</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>Pilhas aprovadas pelo INMETRO: Testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>As pilhas Elgin têm ótima relação custo/benefício, você economiza e ainda conta com pilhas de alta qualidade.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Validade de 3 anos.</li><li>Voltagem 1.5V.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "40 AAA baterias necessárias. (inclusas)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Zinco",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "40.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Elgin-PILHA-ZINCO-COMUM-Laranja/dp/B09LD48ZZ4/ref=zg_bs_g_electronics_d_sccl_29/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-29",
    "title": "Duracell Pilhas Moeda CR2032 Pack 2 Unidades – Ideal para Placas Mãe e Controles Automotivos",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71TJ3Ud6gtL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 19.9,
    "price_original": 24.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 26590,
    "coupon_code": null,
    "description": "<ul><li>As pilhas moeda são usadas em chaveiros, controles remotos, chaves de carro, balanças, calculadoras, acessórios vestíveis (como óculos e relógios), entre outros..</li><li>As pilhas moeda são usadas em sensores, equipamentos médicos (medidores de glicemia, termômetros digitais), aparelhos desportivos (medidor de ritmo cardíaco, acessórios de ciclismo), entre outros.</li><li>A embalagem reforçada garante a segurança dos seus filhos: ela só pode ser aberta com uma tesoura.</li><li>A tecnologia de Duracell preserva a energia das pilhas que ainda não foram usadas, por até 10 anos.</li><li>As pilhas moeda Duracell 2032 são fabricadas com lítio de elevada pureza e têm energia de longa duração para diferentes equipamentos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "2 Íon de lítio (necessita de baterias)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "255",
      "Adequação do controle por rádio": "Controles automotivos, Placas-mãe de computador, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Duracell-Pilhas-Unidades-Controles-Automotivos/dp/B08DQQC61G/ref=zg_bs_g_electronics_d_sccl_30/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-30",
    "title": "Escadinha Infantil 2 Degraus, Clingo, Azul",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61H18Yz9FvL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 61.7,
    "price_original": 79.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1107,
    "coupon_code": null,
    "description": "<ul><li>Acesso em Alta: A Escadinha ajuda seu pequeno a alcançar a pia, vaso sanitário e banheira, tornando as tarefas diárias muito mais fáceis!</li><li>Segurança em Primeiro Lugar: Com borracha antiderrapante, sua criança fica segura durante o uso, permitindo que ela suba e desça sem preocupações!</li><li>Multiuso e Prática: Pode ser usada como um banquinho para ajudar mamães na hora do banho, oferecendo versatilidade e praticidade na rotina!</li><li>Compacta e Fácil de Guardar: Seu design inteligente permite que a escada seja armazenada facilmente, ideal para espaços pequenos!</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "27P x 37L x 17A centímetros",
      "Marca": "Clingo",
      "Material": "Polipropileno (PP)",
      "Cor": "Azul",
      "Características especiais": "Base larga para maior estabilidade e segurança., Degraus antiderrapante., Suporta até 80kg"
    },
    "affiliate_url": "https://www.amazon.com.br/Escadinha-infantil-degraus-Clingo-Azul/dp/B07GF35WDR/ref=zg_bs_g_furniture_d_sccl_31/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-31",
    "title": "Stanley Garrafa Térmica Aerolight Transit Black | 591ml",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41FFVP84XnL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 160.13,
    "price_original": 259.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2138,
    "coupon_code": null,
    "description": "<ul><li>DESIGN LEVE - Um terço mais leve do que as garrafas de aço inoxidável normais, graças à tecnologia AeroLight. Torna esta garrafa de água ideal para colocar na sua bolsa de trabalho, escola, faculdade ou academia.</li><li>DURÁVEL E ISOLADA - Fabricado em aço inoxidável 18/8 com isolamento a vácuo de parede dupla para um desempenho térmico duradouro. Tanto para bebidas quentes ou frias; mantém o seu café ou chá quente durante 8 horas, a sua água ou refrigerante gelados durante 12 horas e frescos durante 40 horas.</li><li>À PROVA DE VAZAMENTOS E SEGURA – Possui uma tampa com bloqueio e abertura para beber, garantindo transporte à prova de vazamentos, e a base estreita se encaixa na maioria dos porta-copos de carro.</li><li>MANUTENÇÃO FÁCIL - Pode ser lavada na máquina de lavar louça e não contém BPA.</li><li>STANLEY - Com uma rica história de 100 anos, a marca Stanley nos trouxe o isolamento a vácuo e revolucionou a maneira como consumimos bebidas. Do quente ao frio, os produtos Stanley são icônicos, duráveis e feitos para as aventuras modernas. Prepare-se para começar a sua.</li></ul>",
    "informacoes_produto": {
      "Marca": "Stanley",
      "Capacidade": "591 ml",
      "Cor": "Black",
      "Adequação do controle por rádio": "Café",
      "Características especiais": "Leve, À prova de vazamentos"
    },
    "affiliate_url": "https://www.amazon.com.br/Stanley-Garrafa-T%C3%A9rmica-Aerolight-Transit/dp/B0FR5D4ZYY/ref=zg_bs_g_kitchen_d_sccl_32/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-32",
    "title": "ELG, PWC-R5, PowerCube, Multiplicador 5 Tomadas, Disjuntor Integrado de 10A, Filtro de Linha com Protetor de Surto, Bivolt, Branco e Verde",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51CsZOBHOoL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 50.0,
    "price_original": 91.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5348,
    "coupon_code": null,
    "description": "<ul><li>MULTIPLICADOR DE TOMADAS: Compacto, e em formato de cubo, o PowerCube transforma uma única tomada em 5 pontos de energia, que podem ser utilizadas simultaneamente para carregamento rápido de dispositivos eletrônicos.</li><li>TRAVA PARA CRIANÇAS: O sistema Child Lock garante proteção extra ao impedir a inserção acidental de objetos nas tomadas, liberando a entrada apenas quando os pinos são inseridos simultaneamente.</li><li>DESIGN PREMIADO: Com design premiado internacionalmente, sua estrutura única permite conectar todos os plugues ao mesmo tempo, sem bloqueios entre si. É ideal para uso em residências, escritórios e hotéis.</li><li>QUALIDADE PREMIUM: Fabricado em policarbonato antichamas, com conectores em cobre de alta pureza e certificação pelo Inmetro, obtenha segurança e eficiência em um produto bivolt de alto padrão.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Marca": "ELG",
      "Cor": "Verde e Branco",
      "Total de tomadas de energia": "5",
      "Tensão": "110 Volts, 220 Volts",
      "Características especiais": "Proteção de sobretensão"
    },
    "affiliate_url": "https://www.amazon.com.br/Multiplicador-Tomadas-PowerCube-Elg-PWC-R5/dp/B076HYZQMW/ref=zg_bs_g_electronics_d_sccl_33/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-34",
    "title": "PIX Suporte de TV Fixo Universal 10 a 100 Polegadas Compacto Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/617C5sIk3sL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 9.4,
    "price_original": 12.5,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1242,
    "coupon_code": null,
    "description": "<ul><li>Suporte Fixo Universal 10 a 100 Polegadas – Compatível com a maioria das TVs, ideal para otimizar espaço em salas, quartos e ambientes comerciais.</li><li>Capacidade de até 80 kg – Estrutura reforçada para suportar TVs grandes com estabilidade e segurança.</li><li>Instalação fácil – Acompanha kit completo de buchas e parafusos, garantindo praticidade na montagem.</li><li>Compatível com padrão VESA 75x75 a 800x400 mm – Ajuste simples a diferentes modelos e tamanhos de TVs sem complicações.</li><li>Garantia de 5 anos – Confiabilidade e durabilidade asseguradas para uso residencial e profissional.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "PIX",
      "Material": "Metal",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/PIX-Suporte-Universal-Polegadas-Compacto/dp/B0CM27NSBG/ref=zg_bs_g_electronics_d_sccl_35/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-37",
    "title": "Tramontina JOGO FACAS INOX 4PC PLENUS PRE, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71EvJYnDRYL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 29.9,
    "price_original": 37.61,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 12789,
    "coupon_code": null,
    "description": "<ul><li>Jogo de Facas Tramontina Plenus com Lâminas em Aço Inox e Cabos de Polipropileno Preto 04 Peças</li><li>Número de modelo: 23498064</li><li>Nome de modelo: PLENUS</li><li>Tipo de produto: HOME</li></ul>",
    "informacoes_produto": {
      "Material da lâmina": "Aço inoxidável",
      "Marca": "Tramontina",
      "Cor": "Preto",
      "Material do cabo": "Polipropileno",
      "Borda da lâmina": "Plana"
    },
    "affiliate_url": "https://www.amazon.com.br/Tramontina-JOGO-FACAS-PLENUS-Preto/dp/B09XFD2YMF/ref=zg_bs_g_kitchen_d_sccl_38/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-38",
    "title": "Agratto 784 - Chaleira Eletrica Inox, 220v, 1,8 Litro, Preto/inox",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51CmxAPMOML._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 57.65,
    "price_original": 108.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 17722,
    "coupon_code": null,
    "description": "<ul><li>Verifique a voltagem antes de comprar o produto para certificar-se de que corresponde à da sua região</li><li>Tampa com trava de segurança</li><li>Base de contato separada</li><li>Com trava de segurança</li><li>Botão liga/desliga</li><li>Base separada</li><li>Luz LED operacional</li><li>Desliga automaticamente</li></ul>",
    "informacoes_produto": {
      "Marca": "Agratto",
      "Capacidade": "1,8 litros",
      "Material": "Aço inoxidável, Plástico",
      "Cor": "Preto/Inox",
      "Informações de embalagem": "RM"
    },
    "affiliate_url": "https://www.amazon.com.br/CHALEIRA-ELETRICA-AGRATTO-Agratto-784/dp/B075TGQVHT/ref=zg_bs_g_kitchen_d_sccl_39/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-39",
    "title": "Jogo de 6 Copos Sofia, Vidro Transparente, 450ml, Design Canelado Vertical, para Água, Sucos e Drinks",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71+tqBymsSL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 29.9,
    "price_original": 44.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 20,
    "coupon_code": null,
    "description": "<ul><li>DESIGN CANELADO ELEGANTE: O acabamento canelado vertical confere sofisticação e um efeito visual refinado, valorizando a apresentação das bebidas.</li><li>JOGO COMPLETO COM 6 COPOS: Conjunto com 6 copos Sofia de 450ml cada, ideais para uso diário ou ocasiões especiais com estilo e praticidade.</li><li>VERSATILIDADE: Perfeitos para servir água, sucos, refrigerantes, drinks e coquetéis, combinando com diferentes estilos de mesa e ambientes.</li><li>VIDRO TRANSPARENTE DE ALTA QUALIDADE: Fabricados em vidro resistente e transparente, unindo beleza e durabilidade para o dia a dia.</li><li>ESTILO MODERNO: O design sofisticado combina perfeitamente com cozinhas modernas, mesas postas e ambientes que valorizam a elegância.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATAO",
      "Material": "Vidro de borossilicato",
      "Cor": "Transparente",
      "Capacidade": "90 ml",
      "Características especiais": "Parede Dupla Isolante"
    },
    "affiliate_url": "https://www.amazon.com.br/Sofia-Transparente-Design-Canelado-Vertical/dp/B0H5TGYNPL/ref=zg_bs_g_kitchen_d_sccl_40/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-40",
    "title": "Melitta Filtro de Papel 102 - 30 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81ZrxBKCaCL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 4.49,
    "price_original": 0.15,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 648,
    "coupon_code": null,
    "description": "<ul><li>Muita tecnologia para o seu café ficar sempre fresquinho e para você sentir mais a vida. Possuem microfuros e dupla costura/ disponível nos tamanhos 100 (200ml ou 4 xícaras ou 1 caneca - ideal para o preparo individual), 102 (800ml ou 16 xícaras) e 103 (1000ml ou 20 xícaras)</li><li>Tamanho 102 (ideal para preparar 800ml ou 16 xícaras de café)</li><li>Contem 30 filtros de papel</li><li>Único com microfuros</li></ul>",
    "informacoes_produto": {
      "Material": "Papel",
      "Marca": "Melitta",
      "Forma": "Cone",
      "Número de peças": "1",
      "Dispositivos compatíveis": "Cafeteira"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-para-Caf%C3%A9-102-Melitta/dp/B078XNNYG6/ref=zg_bs_g_kitchen_d_sccl_41/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-41",
    "title": "Adaptador de Tomada Universal Para Viagem Padrão Internacional Europa UK Asia EUA JP AU EU Europeu 3 Pinos Mais de 150 Países Bivolt Trava de Segurança Portátil Ajustável Super PREMIUM",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61kqk9xBg1L._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 19.9,
    "price_original": 109.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 960,
    "coupon_code": null,
    "description": "<ul><li>🌍 Adaptação Total em +150 Países Viaje com liberdade total! Com suporte para os plugues dos tipos A, B, C, D, E, F, G e I, este adaptador universal é compatível com mais de 150 países — incluindo Estados Unidos, Reino Unido, Japão, Austrália e toda a União Europeia. Ideal para quem viaja a trabalho ou lazer e não quer correr riscos com conectividade.</li><li>⚡ Tecnologia Bivolt Inteligente Compatível com tensões de 110V a 220V, o adaptador ajusta automaticamente a voltagem local, protegendo seus dispositivos contra picos de energia. Sem necessidade de ajustes manuais, sem riscos de queima — conecte e relaxe.</li><li>🧳 Compacto e Portátil – Cabe em Qualquer Espaço Leve, dobrável e fácil de guardar. Ideal para malas de mão, mochilas ou estojos de eletrônicos. O design inteligente com plugues retráteis evita volume desnecessário e é perfeito para o dia a dia ou viagens longas.</li><li>🛡️ Segurança de Ponta: Proteção Total Contra Sobrecarga Equipado com sistemas de proteção contra curto-circuito, sobrecarga e superaquecimento, garantindo a segurança dos seus dispositivos e tranquilidade durante o uso, em qualquer lugar do mundo.</li><li>💎 Durabilidade Profissional com Acabamento Premium Fabricado com materiais de alta qualidade, resistente ao desgaste diário e a impactos leves. Perfeito para uso recorrente por viajantes frequentes, empresários e famílias.</li><li>💎 Pinos retrateis</li><li>💎 LED indicador de energia.</li></ul>",
    "informacoes_produto": {
      "Marca": "Genérico",
      "Cor": "branco",
      "Tensão de saída": "220 Volts",
      "Tipo de plugue": "Tipo C, Tipo E, Tipo F",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Adaptador-Universal-Internacional-Seguran%C3%A7a-Ajust%C3%A1vel/dp/B0F1BS14FV/ref=zg_bs_g_electronics_d_sccl_42/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  },
  {
    "asin": "index-49",
    "title": "Hario Filtro De Papel para Coador de Café Branco V60 Tamanho 02 Pacote Com 100 Unidades Original Japão",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61iXYB9ObhL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 42.9,
    "price_original": 53.55,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 14269,
    "coupon_code": null,
    "description": "<ul><li>Formato cônico \"V\" perfeito para os coadores Hario V60</li><li>Feito de papel celulósico de alta qualidade</li><li>Compatível com coador Hario V60 tamanho 02 (2-4 xícaras)</li><li>Quantidade: 10 unidades por embalagem</li><li>Passa por processo de branqueamento com oxigênio</li></ul>",
    "informacoes_produto": {
      "Material": "Papel",
      "Marca": "HARIO",
      "Forma": "Cone",
      "Número de peças": "100",
      "Dispositivos compatíveis": "Cafeteira"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-Branco-unidades-Tamanho-Coador/dp/B001U7EOYA/ref=zg_bs_g_kitchen_d_sccl_50/142-1093977-3967510?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T01:26:04.000Z",
    "spotlight": false
  }
];
